baseurl = "https://likan.info/"
languageCode = "en-us"
title = "Likan Zhan | 战立侃"
theme = "hugo-ivy"
googleAnalytics = "UA-112592341-1"
disqusShortname = "https-likanzhan-github-io"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
MetaDataFormat = "yaml" # format of a new post
enableGitInfo = true

[[menu.main]]
    name = "English"
    url = "/en／"
    weight = 1

[[menu.main]]
    name = "中文"
    url = "/cn/"
    weight = 2

[[menu.main]]
    name = "FLAG"
    url = "http://probstatr.likan.info"
    weight = 3

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2

[[menu.en]]
    name = "Teaching"
    url = "/en/teach/"
    weight = 3

[[menu.en]]
    name = "CV"
    url = "/en/cv/LZhan"
    weight = 4

[[menu.en]]
    name = "Blog"
    url = "/en/post/"
    weight = 5

[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 6

[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2

[[menu.cn]]
    name = "著作"
    url = "http://probstatr.likan.info"
    weight = 3

[[menu.cn]]
    name = "研究"
    url = "/cn/research/"
    weight = 4

[[menu.cn]]
    name = "读书"
    url = "/cn/read/"
    weight = 5

[[menu.cn]]
    name = "博客"
    url = "/cn/post/"
    weight = 6

[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 7

[params]
    description = "Likan Zhan's personal website"
    footer = "&copy; [Likan Zhan](/) 2017 - 2018 | [Github](https://github.com/likanzhan) | [Twitter](https://twitter.com/likanzhan) | [Weibo](http://weibo.com/1763551555)"
    disqusURL = "https://likanzhan.github.io"
    customJS = ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]
    githubContentURL = "https://github.com/rbind/likan/edit/master/content/"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"
    dateFormat = "2006-01-02" # "2006-01-02, Mon, "

[params.author]
      en = "Likan Zhan"
      cn = "战立侃"

[params.logo.en]
     img = "/logo/bodhi.png"
     url = "/"
     alt = "Likan Zhan"
     tag = ""

[params.lang.edit]
     cn = "编辑"
[params.lang.license]
     cn = "版权"
[params.lang.subscribe]
     cn = "订阅"
