BaseRUL = "https://likan.info/"
relativeurls = true
languageCode = "en-us"
title = "Likan | 侃侃迩行"
theme = "hugo-lithium-theme"
googleAnalytics = "google analytics"
disqusShortname = "https-likanzhan-github-io"
MetaDataFormat = "yaml" # format of a new post
# SectionPagesMenu = "main"
hasCJKLanguage = true  # .WordCount works correctly for chinese
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[[menu.main]]
    name = "English"
    url = "/en／"
    weight = 1

[[menu.main]]
    name = "中文"
    url = "/cn/"
    weight = 2

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2

[[menu.en]]
    name = "Teaching"
    url = "/en/teach/"
    weight = 3

[[menu.en]]
    name = "CV"
    url = "/en/cv/LZhan"
    weight = 4

[[menu.en]]
    name = "Blog"
    url = "/en/post/"
    weight = 5

[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 6

[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2

[[menu.cn]]
    name = "研究"
    url = "/cn/research/"
    weight = 3

[[menu.cn]]
    name = "读书"
    url = "/cn/read/"
    weight = 4

[[menu.cn]]
    name = "博客"
    url = "/cn/post/"
    weight = 5

[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 6

[params]
    author = "Likan Zhan"
    intro = false
    headline = "headline"
    description = "Web description"
    githubContentURL = "https://github.com/rbind/likan/edit/master/content/"
    # options for highlight.js (version, additional languages, and theme)
    dateFormat = "2006-01-02" # "2006-01-02, Mon, "
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    disqusURL = "https://likanzhan.github.io"
    customCSS = ["css/custom.css"]
    customJS = ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]

[params.logo]
  url = "bodhi.png"
  width = 100
  height = 100
  alt = "Logo"

[params.social]
  twitter = "likanzhan"
  weibo = "zhanlikan"
  github = "likanzhan"
  email = "zhanlikan@hotmail.com"

[Taxonomies]
  tag = "tags"
